### ISSUE TITLE
something about dotfiles

### ISSUE THREAD

**Issue by JinweiClarkChao** [hanjianwei/dotfiles#1]
关于电脑上`dotfiles`的管理，我感觉自己一直没有用对正确的姿势。我尝试过几种方法：

+ 在GitHub上建一个repo，clone到本地，如果其中的某些文件发生了修改，手动维护。

+ 尝试过[fresh](https://github.com/freshshell/fresh#readme)，但是我似乎还是get不到fresh的精华。

我看您的这个repo，似乎是可以把本地的文件自动和GitHub上同步。您能不能把您的这套方法细说一下，然后给出一个比较明了的Tutorial。

Thanks. :smile:

**Comment by hanjianwei** [comment]
这个repo叫dotfiles其实有点不准确，其实我是想用它来自动安装、配置系统（Mac）。这里只说说dotfiles相关的内容吧。

基本的方法其实很简单，把所有的配置文件放在一个目录（比如这里是`HOME`），然后通过符号链接链接到正确的位置。举个例子，对于vim的配置文件`.vimrc`，会把它放在`HOME/.vimrc`，然后创建一个符号链接到`~/.vimrc`，这样就可以统一管理所有的配置文件了。具体的介绍可以参照[Mackup](https://github.com/lra/mackup)。

和Mackup相比，我的dotfiles里面的配置文件其实分成了两部分，对于vim、Emacs之类的配置文件，都是放在github保存的；而对于有些比较私密的文件（比如`.ssh`）或者变动比较快的、二进制的不适合用git管理的，我都是放在dropbox里面的。项目里的`backends`其实就是定义了哪些文件应该放在github，哪些应该放在dropbox。

至于其它部分，基本上都是一些脚本，用来方便创建符号链接、备份已有的配置文件的。

**Comment by JinweiClarkChao** [comment]
我去试用了一下Markup，感觉已经能够满足自己的需求了。谢谢 :smile:
